dev_croix_rouge/urls.py
from django.contrib import admin
from django.urls import path, include
from CoronApp.views import DemandeView, ListDemandes, index, DemandeFormView, cloture, validate, assign_view, \
    set_assign, refuse, RetourView, DemandeEditView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('demandes/', ListDemandes.as_view(), name='demandes'),
    path('demande/<pk>', DemandeView.as_view(), name='demande'),
    path('demande/<pk>/edit', DemandeEditView.as_view(), name='demande-edit'),
    path('demande/<pk>/assign/<t>', assign_view, name='assign'),
    path('demande/<pk>/assign_ressource', set_assign, name='assign-ressource'),
    path('demande/<pk>/cloture', cloture, name='cloture'),
    path('demande/<pk>/validate', validate, name='validate'),
    path('demande/<pk>/refuse', refuse, name='refuse'),
    path('demande/<pk>/retour', RetourView.as_view(), name='retour-form'),
    path('newdemande/', DemandeFormView.as_view(), name='demande-form'),
    path('', index),
]

CoronApp/models.py
# coding=utf-8
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django_fsm import FSMField, transition, FSMKeyField
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

# Create your models here.


ETATS = {
    ("cree", "Créée"),
    ("valide", "Validée"),
    ("provisionne", "Provisionnée"),
    ("cloture", "Cloturée"),
    ("refuse", "Refusée"),
    ("termine", "Terminée")
}


class Profil(models.Model):
    class Meta:
        permissions = [
            ('is_chef', 'User is chef'),
        ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Profil")
    tel = models.CharField(max_length=12)

    def __str__(self):
        return self.user.get_full_name()


class Demande(models.Model):
    class Meta:
        ordering = ['date_debut', 'responsable', 'titre']
        permissions = [
            ('can_validate', 'Can validate request'),
            ('can_cloture', 'Can cloture'),
            ('can_edit', 'Can edit a demand'),
            ('can_refuse', 'Can refuse a demand'),
            ('can_finish', 'Can add feedback')
        ]

    created_at = models.DateTimeField(verbose_name="Date de création de la demande", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Date de dernière édition", auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    etat = FSMField(default="cree", choices=ETATS)  # TODO : check https://github.com/viewflow/django-fsm

    # Infos générales

    titre = models.CharField(verbose_name="Titre de la demande", max_length=128)
    date_debut = models.DateTimeField(verbose_name="Date et heure de début de l'opération")
    date_fin = models.DateTimeField(verbose_name="Date et heure de fin de l'opération")
    lieu_deroulement = models.CharField(verbose_name="Lieu de la mission", max_length=255)
    responsable = models.ForeignKey(Profil, on_delete=models.SET_NULL,
                                    null=True,
                                    verbose_name="Responsable de la mission")
    description = models.CharField(verbose_name="Description succincte", max_length=300)

    # Effectifs
    nb_benevoles = models.IntegerField(verbose_name="Nombre de bénévoles demandés", default=0)
    date_presence_debut = models.DateTimeField(verbose_name="Date et heure du rendez-vous pour les bénévoles")
    date_presence_fin = models.DateTimeField(verbose_name="Date et heure de fin de présence pour la mission")
    lieu_rdv = models.CharField(verbose_name="Lieu de rendez-vous pour les bénévoles", max_length=255)
    qualifications = models.TextField(verbose_name="Qualifications spécifiques demandées", blank=True)

    # Subsistances
    nb_repas = models.IntegerField(verbose_name="Nombre de repas nécessaires", default=0)
    lieu_repas = models.CharField(verbose_name="Lieu de la prise de repas", max_length=255, blank=True)
    commentaires_repas = models.TextField(verbose_name="Commentaires/Régimes alimentaires particuliers", blank=True)

    # Vehicules
    nb_transport = models.IntegerField(verbose_name="Bénévoles à transporter", default=0)
    nb_log = models.IntegerField(verbose_name="Nombre de LOG", default=0)
    nb_vl = models.IntegerField(verbose_name="Nombre de VL", default=0)
    nb_vpsp = models.IntegerField(verbose_name="Nombre de VPSP", default=0)
    commentaire_transport = models.TextField(verbose_name="Demande spécifique", blank=True)

    # Logistique
    nature_chargement = models.CharField(verbose_name="Nature du chargement",
                                         help_text="Taille, poids, conditionnement",
                                         max_length=255, blank=True)
    est_alimentaire = models.BooleanField(verbose_name="Contient de l'alimentaire", default=False)
    est_frais = models.BooleanField(verbose_name="Frais", default=False)
    moyens_engages = models.TextField(
        verbose_name="Moyens engagés",
        help_text="[type, nombre, utilisation], [secours, urgence (CAI/CHU/etc.), électriques ("
                  "chauffage/GPE/rallonges/lampes/etc.), soutien (tables/chaise/etc.)]", blank=True)

    # Infos complémentaires
    contact_in_situ = models.CharField(verbose_name="Contact sur place", max_length=255, blank=True)
    tel_in_situ = models.CharField(verbose_name="Téléphone du contact sur place", max_length=12, blank=True)
    description_detaillee = models.TextField(verbose_name="Description détaillée de la mission",
                                             help_text="Chronogramme précis, transport, mise en place etc.")

    @transition(field=etat, source="cree", target="valide",
                permission=lambda instance, user: user.hasPerm('CoronApp.can_validate'))
    def validate(self):
        r = Reponse(demande=self)
        r.save()

    def est_provisionne(self):
        if self.reponse.effectifs_provisionnes and self.reponse.logistique_provisionnes and self.reponse.subsistances_provisionnes and self.reponse.vehicules_provisionnes:
            return True
        return False

    @transition(field=etat, source="valide", target="provisionne", conditions=[est_provisionne])
    def provisionne(self):
        pass  # TODO Il y a quelque chose à faire ?

    @transition(field=etat, source="cree", target="refuse")
    def refuse(self):
        pass  # TODO Il y a quelque chose à faire ?

    @transition(field=etat, source="provisionne", target="cloture",
                permission=lambda instance, user: user.hasPerm('CoronApp.can_cloture'))
    def cloture(self):
        r = Retour(demande=self)
        r.save()

    @transition(field=etat, source="cloture", target="termine")
    def termine(self):
        pass # TODO Y a t'iL qUelQue ChoSe à fAirE ?

    def __str__(self):
        return "Demande " + self.titre


class Reponse(models.Model):
    class Meta:
        permissions = [
            ('can_assign_vehicules', 'Can assign vehicules'),
            ('can_assign_effectifs', 'Can assign effectifs'),
            ('can_assign_subsistances', 'Can assign subsistances'),
            ('can_assign_logistique', 'Can assign logistique'),
            ('can_comment', 'Can comment'),
        ]

    demande = models.OneToOneField(Demande, on_delete=models.CASCADE, verbose_name="Demande", rel="reponse")
    # Effectifs
    effectifs = models.TextField(verbose_name="Effectif", help_text="Nom Prenom;Nom2 Prenom2;...", blank=True)
    effectifs_provisionnes = models.BooleanField(verbose_name="Effectifs provisionnés", default=False)

    # Véhicules
    vehicules = models.TextField(verbose_name="Véhicules attribués", blank=True)
    vehicules_provisionnes = models.BooleanField(verbose_name="Véhicules provisionnés", default=False)

    # Subsitances
    subsistances = models.TextField(verbose_name="Subsistances", blank=True)
    subsistances_provisionnes = models.BooleanField(verbose_name="Subsistances provisionnées", default=False)

    # Logistique
    logistique = models.TextField(verbose_name="Logistique", blank=True)
    logistique_provisionnes = models.BooleanField(verbose_name="Logistique provisionnée", default=False)

    commentaires = models.TextField(verbose_name="Commentaires", blank=True)

    def provisionneVehicule(self):
        self.vehicules_provisionnes = True
        # TODO faire plus propre
        try:
            self.demande.provisionne()
            self.demande.save()
            print("Demande " + str(self.demande.id) + " provisionnée")
        except:
            pass

    def provisionneLogistique(self):
        self.logistique_provisionnes = True
        # TODO faire plus propre
        try:
            self.demande.provisionne()
            self.demande.save()
            print("Demande " + str(self.demande.id) + " provisionnée")
        except:
            pass

    def provisionneSubsistance(self):
        self.subsistances_provisionnes = True
        # TODO faire plus propre
        try:
            self.demande.provisionne()
            self.demande.save()
            print("Demande " + str(self.demande.id) + " provisionnée")
        except:
            pass

    def provisionneEffectif(self):
        self.effectifs_provisionnes = True
        # TODO faire plus propre
        try:
            self.demande.provisionne()
            self.demande.save()
            print("Demande " + str(self.demande.id) + " provisionnée")
        except:
            pass

    def __str__(self):
        return "Réponse " + self.demande.titre


class Retour(models.Model):
    # Pas de permissions particulières pour l'édition du retour, qui
    # est réalisée obligatoirement par le responsable de la mission

    demande = models.OneToOneField(Demande, on_delete=models.CASCADE, rel="retour")
    created_at = models.DateTimeField(verbose_name="Date de création", auto_now=True)

    # Matériel
    nb_masques_chir = models.IntegerField(verbose_name="Masques chirurgicaux consommés", default=0)
    nb_masques_FFP2 = models.IntegerField(verbose_name="Masques FFP2 consommés", default=0)
    nb_masques_textiles = models.IntegerField(verbose_name="Masques textiles consommés", default=0)
    nb_surblouses = models.IntegerField(verbose_name="Quantité de surblouses consommées", default=0)
    nb_charlottes = models.IntegerField(verbose_name="Quantité de charlottes consommées", default=0)

    # Retour d'expérience
    accident = models.BooleanField(verbose_name="Y a-t-il eu accident/maladie d'un bénévole ?", default=False)
    difficultes = models.TextField(verbose_name="Difficultés rencontrées", blank=True)
    amelioration = models.TextField(verbose_name="Axes d'amélioration", blank=True)
    commentaire = models.TextField(verbose_name="Commentaire de retour de mission", blank=True)

    def __str__(self):
        return "Retour " + self.demande.titre

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <meta charset="UTF-8">

    <title>{% block title %} GestApp {% endblock %}</title>

    <link href="{% static "css/global.css" %}" rel="stylesheet">

    <!-- Bootstrap 4 + JQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <!-- DataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

    <link rel="icon" type="image/png" href="{% static "images/croix_rouge.jpeg" %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <img src="{% static "images/croix_rouge.jpeg" %}" width="60" height=60" alt="Logo Croix-Rouge">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/"> Accueil </a>
                </li>
                {% if request.user.is_authenticated %}
                    {% if perms.CoronApp.add_demande %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'demande-form' %}">Nouvelle demande </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'demandes' %}">Gestion des demandes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/accounts/logout">Se déconnecter </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link " href="/accounts/login">Se connecter </a>
                    </li>
                {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text navbar-right">
                        Groupe : {{ request.user.groups.first }}
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</header>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <link href="{% static "css/cover.css" %}" rel="stylesheet">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

        <main role="main" class="inner cover">
            <h1 class="cover-heading">GestApp</h1>
            <p class="lead">La GestApp a pour but de faciliter la gestion des activités de la Croix Rouge.
                Elle doit permettre de centraliser les demandes de mission ainsi que les affectations des bénévoles et
                du matériel.<br>

            </p>
            <div class="lead">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'demande-form' %}" class="btn btn-lg btn-secondary">Faire une demande</a>
                    <a href="{% url 'demandes' %}" class="btn btn-lg btn-primary" style="float: right">Gérer les
                        demandes</a>
                {% else %}
                    <a href="/accounts/login" class="btn btn-lg btn-primary" style="float: right">Se connecter</a>
                {% endif %}
            </div>
        </main>
        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>Application pour la Croix-Rouge, par <a
                        href="https://gitlab.com/sia-insa-lyon">SIA INSA Lyon</a>. Version {{ version.major }}.{{ version.minor }}</p>
            </div>
        </footer>
    </div>
{% endblock %}